### ISSUE TITLE
Your System in how many countries it operates

### ISSUE THREAD

**Issue by papac** [PapiHack/paytech-php-client#3]
I would like to know: your system in how many countries it operates

We want to integrate the system

**Comment by PapiHack** [comment]
Hi, so its not my system ! it is just a SDK or client API for a local online payment gateway here in Senegal.
je l'ai créé afin de facilité aux autres developpeurs l'intégration de leur API sur des projets PHP.
Aussi je ne sais pas s'il est disponible dans d'autres pays. Vous pouvez visiter leur site à cette adresse pour plus d'infos https://paytech.sn

**Comment by PapiHack** [comment]
Hi, so this is not my system! it's just a client SDK or API client for a local online payment gateway here in Senegal.
I created it to make it easier for other developers to integrate their API into PHP projects.
Also I don't know if it's available in other countries. You can visit their site at this address for more info https://paytech.sn/
